# Custom ByteTrack config for high persistence
tracker_type: bytetrack  # tracker type, ['botsort', 'bytetrack']
track_high_thresh: 0.3    # threshold for the first association
track_low_thresh: 0.1     # threshold for the second association
new_track_thresh: 0.4     # threshold for init new track if the detection does not match any tracks
track_buffer: 180         # buffer to calculate the time when to remove tracks (180 frames = 6 seconds at 30 fps)
match_thresh: 0.9         # threshold for matching tracks
fuse_score: True          # (bool) Fuse detection score with motion/IoU for matching
# min_box_area: 10          # threshold for min box areas(for tracker evaluation, not used for now)
# mot20: False              # for tracker evaluation(not used for now)
